SHELL := /bin/sh
.DEFAULT_GOAL := dev

# 本地开发只把基础设施放进容器；网关本身始终使用当前工作区源码构建并启动。
PODMAN ?= podman
COMPOSE ?= $(PODMAN) compose
COMPOSE_FILE ?= deploy/compose.yml
DEPENDENCY_SERVICES ?= postgres redis clickhouse
DEPENDENCY_WAIT_TIMEOUT_SECONDS ?= 120

POSTGRES_DB ?= aestus_gateway
POSTGRES_USER ?= aestus
POSTGRES_PASSWORD ?= aestus
POSTGRES_HOST ?= 127.0.0.1
POSTGRES_PORT ?= 5432

REDIS_HOST ?= 127.0.0.1
REDIS_PORT ?= 6379

CLICKHOUSE_URL ?= http://127.0.0.1:8123
CLICKHOUSE_DATABASE ?= default
CLICKHOUSE_USER ?= default
CLICKHOUSE_PASSWORD ?= change-me-clickhouse-password

DATABASE_URL ?= postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
REDIS_URL ?= redis://$(REDIS_HOST):$(REDIS_PORT)/0
AESTUS_BIND_ADDR ?= 0.0.0.0:8080
AESTUS_DATABASE_POOL_SIZE ?= 16
AESTUS_BODY_MEMORY_LIMIT_BYTES ?= 1048576
AESTUS_UPSTREAM_RETRY_LIMIT ?= 2
AESTUS_PROVIDER_SESSION_STICKY_TTL_SECONDS ?= 3600
AESTUS_PROVIDER_SCHEDULER_CANDIDATE_LIMIT ?= 32
AESTUS_GPT_UPSTREAM_API_KEY_PROBE_INTERVAL_SECONDS ?= 120
AESTUS_GPT_UPSTREAM_BASE_URL ?= https://chatgpt.com/backend-api/codex
AESTUS_GPT_UPSTREAM_RESPONSES_PATH ?= /responses
AESTUS_PROVIDER_UPSTREAM_CONNECT_TIMEOUT_SECONDS ?= 30
AESTUS_PROVIDER_UPSTREAM_TIMEOUT_SECONDS ?= 120
AESTUS_PROVIDER_UPSTREAM_STREAM_IDLE_TIMEOUT_SECONDS ?= 0
AESTUS_GPT_TOKEN_REFRESH_AHEAD_SECONDS ?= 180
AESTUS_GPT_TOKEN_REFRESH_RETRY_SECONDS ?= 30
AESTUS_GPT_OAUTH_ISSUER ?= https://auth.openai.com
AESTUS_GPT_OAUTH_REDIRECT_URI ?= http://localhost:1455/auth/callback
AESTUS_GPT_OAUTH_SCOPE ?= openid profile email offline_access
AESTUS_GPT_OAUTH_SESSION_TTL_SECONDS ?= 600
AESTUS_GPT_TOKEN_ENDPOINT ?= https://auth.openai.com/oauth/token
AESTUS_CLAUDE_ACCOUNT_RATE_LIMIT_COOLDOWN_SECONDS ?= 120
AESTUS_CLAUDE_UPSTREAM_API_KEY_PROBE_INTERVAL_SECONDS ?= 120
AESTUS_CLAUDE_UPSTREAM_API_KEY_PROBE_MODEL ?= claude-opus-4-8
AESTUS_CLAUDE_UPSTREAM_BASE_URL ?= https://api.anthropic.com
AESTUS_CLAUDE_UPSTREAM_MESSAGES_PATH ?= /v1/messages
AESTUS_CLAUDE_TOKEN_REFRESH_AHEAD_SECONDS ?= 180
AESTUS_CLAUDE_TOKEN_REFRESH_RETRY_SECONDS ?= 30
AESTUS_CLAUDE_OAUTH_AUTHORIZE_URL ?= https://claude.com/cai/oauth/authorize
AESTUS_CLAUDE_OAUTH_REDIRECT_URI ?= https://platform.claude.com/oauth/code/callback
AESTUS_CLAUDE_OAUTH_SCOPE ?= user:profile user:inference user:sessions:claude_code user:mcp_servers user:file_upload
AESTUS_CLAUDE_OAUTH_SESSION_TTL_SECONDS ?= 600
AESTUS_CLAUDE_TOKEN_ENDPOINT ?= https://platform.claude.com/v1/oauth/token
AESTUS_GPT_QUOTA_RECOVERY_SECONDS ?= 18000
AESTUS_CODEX_VERSION_HEADER ?= 0.142.5
AESTUS_REQUEST_LOG_TABLE ?= gateway_request_logs
AESTUS_WEB_DIST_DIR ?= ../web/dist
AESTUS_JWT_SECRET ?= local-dev-change-me
AESTUS_JWT_TTL_SECONDS ?= 604800
AESTUS_ADMIN_USERNAME ?= admin
AESTUS_ADMIN_EMAIL ?= admin@example.com
AESTUS_ADMIN_PASSWORD ?= admin123
AESTUS_ADMIN_INITIAL_QUOTA ?= 1000000
AESTUS_SMTP_HOST ?= smtp.example.com
AESTUS_SMTP_PORT ?= 587
AESTUS_SMTP_USERNAME ?= change-me-smtp-user
AESTUS_SMTP_PASSWORD ?= change-me-smtp-password
AESTUS_SMTP_FROM ?= no-reply@example.com
AESTUS_EMAIL_CODE_TTL_SECONDS ?= 600
AESTUS_EMAIL_CODE_COOLDOWN_SECONDS ?= 60
AESTUS_LOG_DIRECTORY ?= logs
AESTUS_LOG_FILE_NAME ?= aestus-gateway.log
RUST_LOG ?= aestus=info,tower_http=info,axum=info

.PHONY: dev

# 一键启动顺序必须保持为：基础设施 -> 数据库迁移 -> 前端构建 -> 本地网关进程。
# 所有步骤集中在默认目标中，直接执行 make 即可完成本地启动。
dev:
	@set -e; \
	printf '%s\n' '[aestus] 正在通过 Podman Compose 启动 PostgreSQL、Redis 和 ClickHouse...'; \
	env \
		POSTGRES_DB="$(POSTGRES_DB)" \
		POSTGRES_USER="$(POSTGRES_USER)" \
		POSTGRES_PASSWORD="$(POSTGRES_PASSWORD)" \
		CLICKHOUSE_DATABASE="$(CLICKHOUSE_DATABASE)" \
		CLICKHOUSE_USER="$(CLICKHOUSE_USER)" \
		CLICKHOUSE_PASSWORD="$(CLICKHOUSE_PASSWORD)" \
		$(COMPOSE) -f "$(COMPOSE_FILE)" up -d \
			--wait \
			--wait-timeout "$(DEPENDENCY_WAIT_TIMEOUT_SECONDS)" \
			$(DEPENDENCY_SERVICES); \
	printf '%s\n' '[aestus] 依赖服务已全部通过健康检查。'; \
	printf '%s\n' '[aestus] 正在执行 PostgreSQL 数据库迁移...'; \
	env \
		POSTGRES_DB="$(POSTGRES_DB)" \
		POSTGRES_USER="$(POSTGRES_USER)" \
		POSTGRES_PASSWORD="$(POSTGRES_PASSWORD)" \
		$(COMPOSE) -f "$(COMPOSE_FILE)" run --rm migrate; \
	printf '%s\n' '[aestus] PostgreSQL 数据库迁移完成。'; \
	printf '%s\n' '[aestus] 正在构建 Web 管理页面...'; \
	cd web; \
	npm run build; \
	cd ../srv; \
	printf '%s\n' '[aestus] 正在通过 cargo run 构建并启动本地网关，监听地址：$(AESTUS_BIND_ADDR)'; \
	env \
		DATABASE_URL="$(DATABASE_URL)" \
		REDIS_URL="$(REDIS_URL)" \
		CLICKHOUSE_URL="$(CLICKHOUSE_URL)" \
		CLICKHOUSE_DATABASE="$(CLICKHOUSE_DATABASE)" \
		CLICKHOUSE_USER="$(CLICKHOUSE_USER)" \
		CLICKHOUSE_PASSWORD="$(CLICKHOUSE_PASSWORD)" \
		AESTUS_BIND_ADDR="$(AESTUS_BIND_ADDR)" \
		AESTUS_DATABASE_POOL_SIZE="$(AESTUS_DATABASE_POOL_SIZE)" \
		AESTUS_BODY_MEMORY_LIMIT_BYTES="$(AESTUS_BODY_MEMORY_LIMIT_BYTES)" \
		AESTUS_UPSTREAM_RETRY_LIMIT="$(AESTUS_UPSTREAM_RETRY_LIMIT)" \
		AESTUS_PROVIDER_SESSION_STICKY_TTL_SECONDS="$(AESTUS_PROVIDER_SESSION_STICKY_TTL_SECONDS)" \
		AESTUS_PROVIDER_SCHEDULER_CANDIDATE_LIMIT="$(AESTUS_PROVIDER_SCHEDULER_CANDIDATE_LIMIT)" \
		AESTUS_GPT_UPSTREAM_API_KEY_PROBE_INTERVAL_SECONDS="$(AESTUS_GPT_UPSTREAM_API_KEY_PROBE_INTERVAL_SECONDS)" \
		AESTUS_GPT_UPSTREAM_BASE_URL="$(AESTUS_GPT_UPSTREAM_BASE_URL)" \
		AESTUS_GPT_UPSTREAM_RESPONSES_PATH="$(AESTUS_GPT_UPSTREAM_RESPONSES_PATH)" \
		AESTUS_PROVIDER_UPSTREAM_CONNECT_TIMEOUT_SECONDS="$(AESTUS_PROVIDER_UPSTREAM_CONNECT_TIMEOUT_SECONDS)" \
		AESTUS_PROVIDER_UPSTREAM_TIMEOUT_SECONDS="$(AESTUS_PROVIDER_UPSTREAM_TIMEOUT_SECONDS)" \
		AESTUS_PROVIDER_UPSTREAM_STREAM_IDLE_TIMEOUT_SECONDS="$(AESTUS_PROVIDER_UPSTREAM_STREAM_IDLE_TIMEOUT_SECONDS)" \
		AESTUS_GPT_TOKEN_REFRESH_AHEAD_SECONDS="$(AESTUS_GPT_TOKEN_REFRESH_AHEAD_SECONDS)" \
		AESTUS_GPT_TOKEN_REFRESH_RETRY_SECONDS="$(AESTUS_GPT_TOKEN_REFRESH_RETRY_SECONDS)" \
		AESTUS_GPT_OAUTH_ISSUER="$(AESTUS_GPT_OAUTH_ISSUER)" \
		AESTUS_GPT_OAUTH_REDIRECT_URI="$(AESTUS_GPT_OAUTH_REDIRECT_URI)" \
		AESTUS_GPT_OAUTH_SCOPE="$(AESTUS_GPT_OAUTH_SCOPE)" \
		AESTUS_GPT_OAUTH_SESSION_TTL_SECONDS="$(AESTUS_GPT_OAUTH_SESSION_TTL_SECONDS)" \
		AESTUS_GPT_TOKEN_ENDPOINT="$(AESTUS_GPT_TOKEN_ENDPOINT)" \
		AESTUS_CLAUDE_ACCOUNT_RATE_LIMIT_COOLDOWN_SECONDS="$(AESTUS_CLAUDE_ACCOUNT_RATE_LIMIT_COOLDOWN_SECONDS)" \
		AESTUS_CLAUDE_UPSTREAM_API_KEY_PROBE_INTERVAL_SECONDS="$(AESTUS_CLAUDE_UPSTREAM_API_KEY_PROBE_INTERVAL_SECONDS)" \
		AESTUS_CLAUDE_UPSTREAM_API_KEY_PROBE_MODEL="$(AESTUS_CLAUDE_UPSTREAM_API_KEY_PROBE_MODEL)" \
		AESTUS_CLAUDE_UPSTREAM_BASE_URL="$(AESTUS_CLAUDE_UPSTREAM_BASE_URL)" \
		AESTUS_CLAUDE_UPSTREAM_MESSAGES_PATH="$(AESTUS_CLAUDE_UPSTREAM_MESSAGES_PATH)" \
		AESTUS_CLAUDE_TOKEN_REFRESH_AHEAD_SECONDS="$(AESTUS_CLAUDE_TOKEN_REFRESH_AHEAD_SECONDS)" \
		AESTUS_CLAUDE_TOKEN_REFRESH_RETRY_SECONDS="$(AESTUS_CLAUDE_TOKEN_REFRESH_RETRY_SECONDS)" \
		AESTUS_CLAUDE_OAUTH_AUTHORIZE_URL="$(AESTUS_CLAUDE_OAUTH_AUTHORIZE_URL)" \
		AESTUS_CLAUDE_OAUTH_REDIRECT_URI="$(AESTUS_CLAUDE_OAUTH_REDIRECT_URI)" \
		AESTUS_CLAUDE_OAUTH_SCOPE="$(AESTUS_CLAUDE_OAUTH_SCOPE)" \
		AESTUS_CLAUDE_OAUTH_SESSION_TTL_SECONDS="$(AESTUS_CLAUDE_OAUTH_SESSION_TTL_SECONDS)" \
		AESTUS_CLAUDE_TOKEN_ENDPOINT="$(AESTUS_CLAUDE_TOKEN_ENDPOINT)" \
		AESTUS_GPT_QUOTA_RECOVERY_SECONDS="$(AESTUS_GPT_QUOTA_RECOVERY_SECONDS)" \
		AESTUS_CODEX_VERSION_HEADER="$(AESTUS_CODEX_VERSION_HEADER)" \
		AESTUS_REQUEST_LOG_TABLE="$(AESTUS_REQUEST_LOG_TABLE)" \
		AESTUS_WEB_DIST_DIR="$(AESTUS_WEB_DIST_DIR)" \
		AESTUS_JWT_SECRET="$(AESTUS_JWT_SECRET)" \
		AESTUS_JWT_TTL_SECONDS="$(AESTUS_JWT_TTL_SECONDS)" \
		AESTUS_ADMIN_USERNAME="$(AESTUS_ADMIN_USERNAME)" \
		AESTUS_ADMIN_EMAIL="$(AESTUS_ADMIN_EMAIL)" \
		AESTUS_ADMIN_PASSWORD="$(AESTUS_ADMIN_PASSWORD)" \
		AESTUS_ADMIN_INITIAL_QUOTA="$(AESTUS_ADMIN_INITIAL_QUOTA)" \
		AESTUS_SMTP_HOST="$(AESTUS_SMTP_HOST)" \
		AESTUS_SMTP_PORT="$(AESTUS_SMTP_PORT)" \
		AESTUS_SMTP_USERNAME="$(AESTUS_SMTP_USERNAME)" \
		AESTUS_SMTP_PASSWORD="$(AESTUS_SMTP_PASSWORD)" \
		AESTUS_SMTP_FROM="$(AESTUS_SMTP_FROM)" \
		AESTUS_EMAIL_CODE_TTL_SECONDS="$(AESTUS_EMAIL_CODE_TTL_SECONDS)" \
		AESTUS_EMAIL_CODE_COOLDOWN_SECONDS="$(AESTUS_EMAIL_CODE_COOLDOWN_SECONDS)" \
		AESTUS_LOG_DIRECTORY="$(AESTUS_LOG_DIRECTORY)" \
		AESTUS_LOG_FILE_NAME="$(AESTUS_LOG_FILE_NAME)" \
		RUST_LOG="$(RUST_LOG)" \
		cargo run
